### ISSUE TITLE
HomeMode

### ISSUE THREAD

**Issue by matze1708** [instalator/ioBroker.synology#10]
Hi,

Is it possible to switch HomeMode on and off trough your Adapter?

Is it also possible to find out actual status of homeMode?

Thanks for help.

**Comment by instalator** [comment]
The driver supports all APIs.

**Comment by matze1708** [comment]
Where can i find a example for this?

**Comment by instalator** [comment]
Unfortunately, this method works only with version Surveillance Station 8.1.0, and the driver uses 6.0.2

**Comment by Weezelchen** [comment]
Downgraded to Surveillance 8.1.0-5406 , Adapter API is 6.0.2 , but there is no HomeMode Object.
The Adapter was also reinstalled, but no Success :( 

Any Ideas? I need that Object for the VIS Page ;)

Thx :)

**Comment by instalator** [comment]
added
