### ISSUE TITLE
Adapter not connected with Synology

### ISSUE THREAD

**Issue by FabianHM** [instalator/ioBroker.synology#15]
Hello,
I like the functions of this Adapter, but most of the Time the status of the adapter is yellow, 
Adapter not connected with Synology.
Is this a known problem?

Greetings
Fabian

**Comment by instalator** [comment]
I do not have any NAS when. This week I collected it myself. Now I will add the adapter and fix the errors in it.

**Comment by FabianHM** [comment]
Is there a new version? I like to call me a tester. let me know if I have something to do ;-)

**Comment by FabianHM** [comment]
As already offered, I would like to test, if you have no NAS for the treatment. Unfortunately, the adapter makes no sense, which is why I disable it now.

**Comment by instalator** [comment]
Reduce polling time

**Comment by FabianHM** [comment]
and where do I put these?

**Comment by FabianHM** [comment]
now it works fine
