### ISSUE TITLE
Object without funtions

### ISSUE THREAD

**Issue by pfuhsy** [instalator/ioBroker.synology#16]
I've got a Synology NAS DS115j for backup. This NAS is always completely shut down except for one day of the week, but the installed Synology adapter in iobroker always displays true in the "info / connection" object. Do I understand the value wrong? There are also two buttons called "commands/ Reboot and Shut down", which have no functions at all.

Greetings

**Comment by pfuhsy** [comment]
Hi,

is anybody working on this?

Greeting

**Comment by instalator** [comment]
fixed
