### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [instalator/ioBroker.synology#25]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/instalator/ioBroker.synology

- [ ] [E114] No adapter are allowed in the repo without admin3 support
- [ ] [E801] No repository about text found. Please go to "https://github.com/instalator/ioBroker.synology", press the first "Edit" button you will find on the page and add the description.
- [ ] [E802] No topics found in the repository. Please go to "https://github.com/instalator/ioBroker.synology" and press "Manage topics"
- [ ] [E604] No "## License" found in README.md
- [ ] [E701] No actual year found in LICENSE. Please add "Copyright (c) 2017-2020 instalator <vvvalt@mail.ru>" at the start of LICENSE

I have also found warnings that may be fixed if possible.

- [ ] [W113] Adapter should support compact mode

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by ioBrokerChecker** [comment]
Do you need help fixing the bugs?

**Comment by instalator** [comment]
RE-CHECK!
