### ISSUE TITLE
DEBUG RES ERROR : code(103)

### ISSUE THREAD

**Issue by 7egacy** [instalator/ioBroker.synology#32]
Nach dem letzten Update bekomme ich folgende Fehlermeldung im Log

  |   |   |  
-- | -- | -- | --
synology.0 | 2020-04-30 19:45:16.778 | error | (17545) *** DEBUG RES ERROR : code(103) The requested method does not exist

Nutze die Version 0.1.1 des Adapters auf einem Raspberry Pi 4 mit Node.js v10.20.1 und dem js controller 3.0.20

**Comment by instalator** [comment]
Update from github

**Comment by instalator** [comment]
Please reinstall adapter

**Comment by 7egacy** [comment]
Version 0.1.2 work great, thank you. HomeMode switch is a great Feature!
