### ISSUE TITLE
 DEBUG RES ERROR : code(102) The requested API does not exist

### ISSUE THREAD

**Issue by tobasium** [instalator/ioBroker.synology#33]
Please add API 6.2.3 thanks

**Comment by MMeinhardt1** [comment]
Hi,

i have the same error. I had selected API 6.2.2 with DSM 6.2.2

Thanks

**Comment by instalator** [comment]
Ask the author of the syno package

**Comment by instalator** [comment]
I temporarily made a workaround. Try reinstalling and testing.

**Comment by tobasium** [comment]
For me now it works fine thanks
