### ISSUE TITLE
2 Factor Authentification

### ISSUE THREAD

**Issue by Loni78** [instalator/ioBroker.synology#34]
After the last update I‘m not able to connect the adapter with my both Synology NAS. The logfile display reads „ 1579) Error - Error: Failed to authenticate 2-step verification code“

**Comment by instalator** [comment]
What version did it work on?

**Comment by Loni78** [comment]
Now I‘m working with 6.0.2.

**Comment by instalator** [comment]
> Now I‘m working with 6.0.2.

What version of the adapter worked successfully with two-factor?

**Comment by instalator** [comment]
> After the last update I‘m not able to connect the adapter with my both Synology NAS. The logfile display reads „ 1579) Error - Error: Failed to authenticate 2-step verification code“

Update using a github and specify the secret word in the adapter settings

**Comment by xADDRx** [comment]
Same Problem:(13180) sendPolling - syno[dsm][getPollingData] Error -Error: Failed to authenticate 2-step verification code.

i update using git but dosent work.

**Comment by instalator** [comment]
> Same Problem:(13180) sendPolling - syno[dsm][getPollingData] Error -Error: Failed to authenticate 2-step verification code.
> 
> i update using git but dosent work. i try many codes
Did you write a secret word? Is the user in the Administrators group?

![image](https://user-images.githubusercontent.com/11523624/80991498-590a2e00-8e62-11ea-84e6-1aa032f5d76c.png)

**Comment by instalator** [comment]
fixed 0.1.7

**Comment by xADDRx** [comment]
(26291) *** ERROR : src: sendPolling code: undefined message: syno[dsm][getPollingData] Error -Error: Failed to authenticate 2-step verification code

Code is ok, admin user is in group but doesnt work for me. i try http and https

**Comment by instalator** [comment]
https://github.com/instalator/ioBroker.synology/blob/master/docs/en/template.md

**Comment by xADDRx** [comment]
THANK YOU!!! I Just use a normal Code. Nice Work!!
