### ISSUE TITLE
(12888)Error - Error: No such account or incorrect password

### ISSUE THREAD

**Issue by Thomas1305** [instalator/ioBroker.synology#36]
I am using the dsm Version 6.2.2 and the Adapter version 0.1.2.
I tried a new user on synology (admin, no admin), played around with the User rights.
No succsess.
There is also the problem with the 2-factor-verification, discussed in the other issue.

**Comment by Jogi2020** [comment]
I have the same issue. DS215j ; DSM 6.2.2-24922 Update 4 ; Mode HTTP Port 5000
It has not been working since Adapter version 0.1.0.
This time I have 0.1.2

**Comment by instalator** [comment]
send me debug log

**Comment by Thomas1305** [comment]
Here is my debug log
![image](https://user-images.githubusercontent.com/46224531/80863268-56011900-8c7b-11ea-9964-ae509ff0e35d.png)

**Comment by instalator** [comment]
Update using a github and specify the secret word in the adapter settings

**Comment by Thomas1305** [comment]
Same issue
![image](https://user-images.githubusercontent.com/46224531/80865179-e47b9780-8c87-11ea-8069-04fadcc86dcc.png)
But after update from git, i got the 2-factor-verficatio
![image](https://user-images.githubusercontent.com/46224531/80865220-31f80480-8c88-11ea-897c-c4d632ec750d.png)

**Comment by Thomas1305** [comment]
Must i give specific user rights in synology?

**Comment by Jogi2020** [comment]
Hello, I also installed the version of Github and now get the double identification button. But the problem is the same.
![image](https://user-images.githubusercontent.com/61438894/80866860-59070400-8c91-11ea-9f48-505e4e6d2e97.png)

**Comment by instalator** [comment]
> Hello, I also installed the version of Github and now get the double identification button. But the problem is the same. What is the difference in authentication between V0.0.4 and V0.1.2. V0.0.4 had worked

V0.0.4 worked with 2 fa?

**Comment by instalator** [comment]
> But after update from git, i got the 2-factor-verficatio

Did you turn it on and set it up?

**Comment by Jogi2020** [comment]
After turn on the double identification it works. Thank you

**Comment by Thomas1305** [comment]
Jogi, do u use a Synology User with 2fa or just activate the Button?

**Comment by Jogi2020** [comment]
I have only activate the Button.

**Comment by instalator** [comment]
> I have only activate the Button.

You have 2 fa not activated on the NAS? in this case, in the settings you do not need to put a checkbox

**Comment by Thomas1305** [comment]
still have no chance to get it run

**Comment by huettmasterTB** [comment]
Same Problem. I have 2 users. the first with 2 FA and another without. dsm Version 6.2.2 and the Adapter version is 0.1.4.

**Comment by Jogi2020** [comment]
For me, that's how it works. For the instalator: Marked in red, port should be in German.
![image](https://user-images.githubusercontent.com/61438894/80916246-cda47600-8d57-11ea-9e55-2c4e4bfe4fbd.png)

**Comment by instalator** [comment]
> Same Problem. I have 2 users. the first with 2 FA and another without. dsm Version 6.2.2 and the Adapter version is 0.1.4.

Reinstal from github and test

**Comment by huettmasterTB** [comment]
> 
> 
> > Same Problem. I have 2 users. the first with 2 FA and another without. dsm Version 6.2.2 and the Adapter version is 0.1.4.
> 
> Reinstal from github and test

no chance. Same Problem again. ioBroker is running in a docker container on my synology NAS.

**Comment by instalator** [comment]
> > > Same Problem. I have 2 users. the first with 2 FA and another without. dsm Version 6.2.2 and the Adapter version is 0.1.4.
> > 
> > 
> > Reinstal from github and test
> 
> no chance. Same Problem again. ioBroker is running in a docker container on my synology NAS.

Did you reinstall or just upgrade?

**Comment by huettmasterTB** [comment]
> > > > Same Problem. I have 2 users. the first with 2 FA and another without. dsm Version 6.2.2 and the Adapter version is 0.1.4.
> > > 
> > > 
> > > Reinstal from github and test
> > 
> > 
> > no chance. Same Problem again. ioBroker is running in a docker container on my synology NAS.
> 
> Did you reinstall or just upgrade?

Reinstall

**Comment by instalator** [comment]
> > 
> > Did you reinstall or just upgrade?
> 
> Reinstall

Does the user specified in the adapter settings have 2fa on the NAS?

**Comment by huettmasterTB** [comment]
> > > Did you reinstall or just upgrade?
> > 
> > 
> > Reinstall
> 
> Does the user specified in the adapter settings have 2fa on the NAS?

No. The User has no 2fa. The checkbox is Not activated in the Adapter Settings. The instance signals green. But the error is still there.

**Comment by instalator** [comment]
> > > > Did you reinstall or just upgrade?
> > > 
> > > 
> > > Reinstall
> > 
> > 
> > Does the user specified in the adapter settings have 2fa on the NAS?
> 
> No. The User has no 2fa. The checkbox is Not activated in the Adapter Settings. The instance signals green. But the error is still there.

Write me telegram @instalator

**Comment by instalator** [comment]
> still have no chance to get it run

Is your user in the administrators group?

**Comment by Thomas1305** [comment]
I have the same problem like huettmaster.
And i played around with the user group, also admin user.
But the problem die not disappear.

**Comment by instalator** [comment]
This answer returns NAS, i.e. he really can not find the user or the password is not correct. This may mean that the user does not have sufficient rights to the NAS. Is your NAS original?

**Comment by Thomas1305** [comment]
Yes its original and the adapter works well with the Version before 0.1.x

**Comment by instalator** [comment]
> Yes its original and the adapter works well with the Version before 0.1.x

Write me telegram
