### ISSUE TITLE
The requested API does not exist

### ISSUE THREAD

**Issue by Nashra-ioB** [instalator/ioBroker.synology#39]
`2020-05-08 17:57:57.196 - info: host.ioBroker "system.adapter.synology.0" enabled
2020-05-08 17:57:57.281 - info: host.ioBroker instance system.adapter.synology.0 started with pid 13070
2020-05-08 17:57:59.686 - info: synology.0 (13070) starting. Version 0.1.8 in /opt/iobroker/node_modules/iobroker.synology, node: v12.16.3
2020-05-08 17:58:05.905 - error: synology.0 (13070) *** ERROR : src: sendPolling code: undefined message: syno[dsm][getPollingData] Error -Error: The requested API does not exist
2020-05-08 17:58:06.637 - error: synology.0 (13070) *** ERROR : src: sendPolling code: undefined message: syno[dsm][getPollingData] Error -Error: The requested API does not exist
2020-05-08 17:58:07.368 - error: synology.0 (13070) *** ERROR : src: sendPolling code: undefined message: syno[dsm][getPollingData] Error -Error: The requested API does not exist
2020-05-08 17:58:08.098 - error: synology.0 (13070) *** ERROR : src: sendPolling code: undefined message: syno[dsm][getPollingData] Error -Error: The requested API does not exist
2020-05-08 17:58:08.158 - info: host.ioBroker "system.adapter.synology.0" disabled`

Model: DS110j
DSM: 5.2-5967 Update 9 (2018)

**Comment by instalator** [comment]
send a debug log and a screenshot of the adapter settings.

**Comment by Nashra-ioB** [comment]
Tested with all Api-Version

`

synology.0 | 2020-05-09 14:03:12.130 | debug | (2753) * No response, read next.
-- | -- | -- | --
synology.0 | 2020-05-09 14:03:11.683 | debug | (2753) * Get info from (firstPoll) api: DSM method: getPollingData params: {}
synology.0 | 2020-05-09 14:03:11.683 | debug | (2753) -----------------------------------------------------------------------------------------------------
synology.0 | 2020-05-09 14:03:11.682 | error | (2753) *** ERROR : src: sendPolling code: undefined message:  syno[dsm][getPollingData] Error -Error: The requested API does not exist
synology.0 | 2020-05-09 14:03:11.681 | debug | (2753) * No response, read next.
synology.0 | 2020-05-09 14:03:10.625 | debug | (2753) system.adapter.admin.0: logging true
synology.0 | 2020-05-09 14:03:07.109 | debug | (2753) system.adapter.admin.0: logging false
synology.0 | 2020-05-09 14:03:07.071 | debug | (2753) * Get info from (firstPoll) api: DSM method: getPollingData params: {}
synology.0 | 2020-05-09 14:03:07.070 | debug | (2753) -----------------------------------------------------------------------------------------------------
synology.0 | 2020-05-09 14:03:04.819 | info | (2753) starting. Version 0.1.8 in /opt/iobroker/node_modules/iobroker.synology, node: v12.16.3
synology.0 | 2020-05-09 14:03:04.045 | debug | (2753) statesDB connected
synology.0 | 2020-05-09 14:03:04.044 | debug | (2753) States connected to redis: 0.0.0.0:9000
synology.0 | 2020-05-09 14:03:04.021 | debug | (2753) States create System PubSub Client
synology.0 | 2020-05-09 14:03:04.018 | debug | (2753) States create User PubSub Client
synology.0 | 2020-05-09 14:03:04.006 | debug | (2753) Redis States: Use Redis connection: 0.0.0.0:9000
synology.0 | 2020-05-09 14:03:04.004 | debug | (2753) objectDB connected
synology.0 | 2020-05-09 14:03:04.000 | debug | (2753) Objects connected to redis: 0.0.0.0:9001
synology.0 | 2020-05-09 14:03:03.977 | debug | (2753) Objects client initialize lua scripts
synology.0 | 2020-05-09 14:03:03.969 | debug | (2753) Objects create User PubSub Client
synology.0 | 2020-05-09 14:03:03.968 | debug | (2753) Objects create System PubSub Client
synology.0 | 2020-05-09 14:03:03.964 | debug | (2753) Objects client ready ... initialize now
synology.0 | 2020-05-09 14:03:03.926 | debug | (2753) Redis Objects: Use Redis connection: 0.0.0.0:9001

`

![synology](https://user-images.githubusercontent.com/63847592/81473369-42672c80-91fe-11ea-9a1a-0e8f3f9a541a.PNG)

**Comment by instalator** [comment]
You have the wrong version of api selected

**Comment by Nashra-ioB** [comment]
I tested it with all versions of the Api.
It doesn't work with anyone

**Comment by instalator** [comment]
Update the adapter with github and send me a debug log. And choose the correct version of api.

**Comment by Nashra-ioB** [comment]
[syno.zip](https://github.com/instalator/ioBroker.synology/files/4604212/syno.zip)

Api 5.2

**Comment by instalator** [comment]
Update the adapter again with github and send me the debug log.

**Comment by Nashra-ioB** [comment]
[syno.zip](https://github.com/instalator/ioBroker.synology/files/4605759/syno.zip)

**Comment by instalator** [comment]
Update the adapter again

**Comment by Nashra-ioB** [comment]
Sorry this is all new to me

[syno.zip](https://github.com/instalator/ioBroker.synology/files/4606096/syno.zip)

**Comment by Nashra-ioB** [comment]
[ioBroker Synology Adapter](https://forum.iobroker.net/topic/33224/iobroker-synology-adapter?page=1)

**Comment by instalator** [comment]
Is something not working?

**Comment by Nashra-ioB** [comment]
Error in Log, see Logfile
`synology.0 | 2020-05-18 14:05:08.595 | error | (24798) *** ERROR : src: sendPolling code: undefined message:  syno[fs][listSharings] Error -Error: The requested API does not exist
`

[syno-log.zip](https://github.com/instalator/ioBroker.synology/files/4643991/syno-log.zip)

**Comment by instalator** [comment]
You have a very old version, some functions will not work.
API is very different on different versions and there is no way to support all versions.

**Comment by Nashra-ioB** [comment]
Ok, thanks for trying it and it's not that bad
that it is not possible.

Sorry, my english is not good :-(

**Comment by instalator** [comment]
Can you write me in telegram? @instalator

**Comment by Gunthervc** [comment]
Same problem after update and API 6.2.3
(7060) *** ERROR : src: function send: [ss][getSnapshotCamera] code: 102 message: The requested API does not exist
