### ISSUE TITLE
Update frequency of each object

### ISSUE THREAD

**Issue by schmaxEs** [instalator/ioBroker.synology#40]
Hi,

First of all THANK YOU for the great job. The adapter runs perfectly.

As I want to use the adapter only for a few data points (e.g. getting CPU and RAM information as well as the recording status of one Surveillance Station Camera) I wanted to ask if there is a possibility to choose

- which object needs to be updated at all (e.g. so I could disable functionalities I do not need such as Media or Download Station -> optimize performance by reducing API polling)
- which object has which update frequency (e.g. high frequency for recording status of camera and lower frequency for other information)

Thanks in advance.
Regards

**Comment by instalator** [comment]
The difference will be in fractions of a second. I do not see the point in this setting.

**Comment by schmaxEs** [comment]
Thank you for answering quickly.
Reason for asking is: Even with refresh time down to 100-1000 ms it is taking about 5 sec to get an update on the recStatus of my camera in Surveillance Station. My idea was to be able to get a quicker update with that by cancelling unnecessary polls.

**Comment by instalator** [comment]
Update the adapter with github

**Comment by schmaxEs** [comment]
Thank you very much - that helps!
