### ISSUE TITLE
missing datapoints

### ISSUE THREAD

**Issue by Ilovegym66** [instalator/ioBroker.synology#43]
since Version 0.1.7 some important datapoints at SurveillanceStation/Cameras are missing, here a example of the objects in version 0.1.7 or lower:
![grafik](https://user-images.githubusercontent.com/36229898/81598345-6de94300-93c7-11ea-866c-01381d818eb3.png)

and here are the actual datapoints with Version 0.1.10:
![grafik](https://user-images.githubusercontent.com/36229898/81598417-8d806b80-93c7-11ea-85f3-83b7aa1d7e0c.png)

Missing objects are:
linkMjpegHttpPath
linkMulticstPath
linkMxpegHttpPath
linkRtspOverHttpPath
linkRtspPath

add it again, please :-)
I have a synology 918+ Api 6.2.2

**Comment by Ilovegym66** [comment]
correction: in Version 0.1.8 are the objects working, higher Versions the objects are gone.. :-(

**Comment by instalator** [comment]
I didn’t change anything, everything works
![image](https://user-images.githubusercontent.com/11523624/82153470-d2a61100-9891-11ea-8170-3a4b3086388c.png)

**Comment by Ilovegym66** [comment]
have you stop the adapter, deleted the objects, and start it again?
the objects are not created any more.. only in version 0.1.8, with a newer 0.1.10 not..

**Comment by instalator** [comment]
Check on version 0.1.12
