### ISSUE TITLE
uncaught exception: Cannot read property 'api' of undefined

### ISSUE THREAD

**Issue by tobasium** [instalator/ioBroker.synology#47]
Hi, for me the instance (since 0.1.9) restart every 60 seconds:

`

synology.0 | 2020-05-18 23:32:57.855 | info | (621) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
synology.0 | 2020-05-18 23:32:57.854 | info | (621) terminating
synology.0 | 2020-05-18 23:32:57.848 | error | (621) TypeError: Cannot read property 'api' of undefined at sendPolling (/opt/iobroker/node_modules/iobroker.synology/main.js:671:59) at queuePolling (/opt/iobroker/node_modules/iobroker.synol
synology.0 | 2020-05-18 23:32:57.847 | error | (621) uncaught exception: Cannot read property 'api' of undefined

Logfile

[iolog syno.txt](https://github.com/instalator/ioBroker.synology/files/4646950/iolog.syno.txt)
`

If you need more info tell me

**Comment by MC-1984** [comment]
I am getting a similar error

`
synology.0 | 2020-05-19 02:03:03.976 | error | at processTimers (internal/timers.js:492:7)
-- | -- | -- | --
synology.0 | 2020-05-19 02:03:03.976 | error | at listOnTimeout (internal/timers.js:549:17)
synology.0 | 2020-05-19 02:03:03.976 | error | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.synology/main.js:1133:13)
synology.0 | 2020-05-19 02:03:03.976 | error | at queuePolling (/opt/iobroker/node_modules/iobroker.synology/main.js:1060:9)
synology.0 | 2020-05-19 02:03:03.976 | error | at sendPolling (/opt/iobroker/node_modules/iobroker.synology/main.js:1069:59)
synology.0 | 2020-05-19 02:03:03.976 | error | (9625) TypeError: Cannot read property 'api' of undefined
synology.0 | 2020-05-19 02:03:03.971 | error | (9625) uncaught exception: Cannot read property 'api' of undefined
`

I have just started using this adapter. Are there no datapoints for disk usage, available space, virtual machines, etc.?

**Comment by instalator** [comment]
> I am getting a similar error

Update from github and check.
		
> I have just started using this adapter. Are there no datapoints for disk usage, available space, virtual machines, etc.?

This data or I did not understand correctly?

![image](https://user-images.githubusercontent.com/11523624/82280646-8524c380-99b9-11ea-925e-341bb06358f8.png)

**Comment by MC-1984** [comment]
I already updated to the github version.

That is all I there is in the DiskStationManager folder:

<img width="2035" alt="Screen Shot 2020-05-19 at 14 13 27" src="https://user-images.githubusercontent.com/58948938/82325137-0476bf00-99db-11ea-99c7-a21e0feed642.png">

**Comment by instalator** [comment]
Everything works for me, without logs I can not help anything.

**Comment by MC-1984** [comment]
Sorry, of course  here is the log (just one error message)

`
synology.0 | 2020-05-19 16:21:54.002 | error | (10259) *** ERROR : src: sendPolling code: undefined message: syno[dsm][getPollingData] Error -Error: Unknown error
-- | -- | -- | --
`

**Comment by instalator** [comment]
probably NAS will return an error for some reason.

**Comment by MC-1984** [comment]
The NAS works perfectly. Any ideas what can cause that?

**Comment by tobasium** [comment]
Hi i make a clean install from github.

Error is there also, restart every 60seconds:

`

synology.0 | 2020-05-19 17:58:49.639 | info | (11837) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
synology.0 | 2020-05-19 17:58:49.637 | info | (11837) terminating
synology.0 | 2020-05-19 17:58:49.632 | error | (11837) TypeError: Cannot read property 'api' of undefined at sendPolling (/opt/iobroker/node_modules/iobroker.synology/main.js:1066:32) at queuePolling (/opt/iobroker/node_modules/iobroker.sy
synology.0 | 2020-05-19 17:58:49.629 | error | (11837) uncaught exception: Cannot read property 'api' of undefined

`
I have a DS1515+
DSM 6.2.3-25426

Node.js
v12.16.3
NPM
6.14.5

If I go back to 1.0.8 the adapter works fine with DSM6.2.2 settings. Found the debug log attached
[iolog syno 202005191812.txt](https://github.com/instalator/ioBroker.synology/files/4651747/iolog.syno.202005191812.txt)

**Comment by instalator** [comment]
> The NAS works perfectly. Any ideas what can cause that?

Reinstall the adapter and test

**Comment by instalator** [comment]
> Hi i make a clean install from github.
> 
> Error is there also, restart every 60seconds:
> 
> `
> 
> synology.0	2020-05-19 17:58:49.639	info	(11837) Terminated (NO_ERROR): Without reason
> synology.0	2020-05-19 17:58:49.637	info	(11837) terminating
> synology.0	2020-05-19 17:58:49.632	error	(11837) TypeError: Cannot read property 'api' of undefined at sendPolling (/opt/iobroker/node_modules/iobroker.synology/main.js:1066:32) at queuePolling (/opt/iobroker/node_modules/iobroker.sy
> synology.0	2020-05-19 17:58:49.629	error	(11837) uncaught exception: Cannot read property 'api' of undefined
> `
> I have a DS1515+
> DSM 6.2.3-25426
> 
> Node.js
> v12.16.3
> NPM
> 6.14.5
> 
> If I go back to 1.0.8 the adapter works fine with DSM6.2.2 settings. Found the debug log attached
> [iolog syno 202005191812.txt](https://github.com/instalator/ioBroker.synology/files/4651747/iolog.syno.202005191812.txt)

Reinstall

**Comment by tobasium** [comment]
Reinstall to 0.1.14

same issue still present restart every 60 seconds 


synology.0 | 2020-05-19 20:20:06.120 | error | (7349) TypeError: Cannot read property 'api' of undefined at sendPolling (/opt/iobroker/node_modules/iobroker.synology/main.js:1066:21) at queuePolling (/opt/iobroker/node_modules/iobroker.syn
-- | -- | -- | --
synology.0 | 2020-05-19 20:20:06.118 | error | (7349) uncaught exception: Cannot read property 'api' of undefined

[iolog-syno 202005192026.txt](https://github.com/instalator/ioBroker.synology/files/4652430/iolog-syno.202005192026.txt)

**Comment by MC-1984** [comment]
I can confirm that the issue still persists in 0.1.14.

**Comment by instalator** [comment]
> I already updated to the github version.
> 
> That is all I there is in the DiskStationManager folder:
> 
> <img alt="Screen Shot 2020-05-19 at 14 13 27" width="2000" src="https://user-images.githubusercontent.com/58948938/82325137-0476bf00-99db-11ea-99c7-a21e0feed642.png">

0.1.15

**Comment by Ilovegym66** [comment]
Thank you, in Version 0.1.15 the fault is gone, works very good here. Well done!
Syno 918+ Version 6.2.3, Node 12.6.3, NPM 6.14.5, js-controller 3.1.4

**Comment by tobasium** [comment]
Hi, 
reboot for me still there after clean install every 60 seconds:


synology.0 | 2020-05-20 10:36:16.288 | error | (16634) TypeError: Cannot read property 'api' of undefined at sendPolling (/opt/iobroker/node_modules/iobroker.synology/main.js:1099:32) at queuePolling (/opt/iobroker/node_modules/iobroker.sy
-- | -- | -- | --
synology.0 | 2020-05-20 10:36:16.287 | error | (16634) uncaught exception: Cannot read property 'api' of undefined

**Comment by MC-1984** [comment]
Same here

**Comment by instalator** [comment]
> Hi,
> reboot for me still there after clean install every 60 seconds:
> 
> synology.0	2020-05-20 10:36:16.288	error	(16634) TypeError: Cannot read property 'api' of undefined at sendPolling (/opt/iobroker/node_modules/iobroker.synology/main.js:1099:32) at queuePolling (/opt/iobroker/node_modules/iobroker.sy
> synology.0	2020-05-20 10:36:16.287	error	(16634) uncaught exception: Cannot read property 'api' of undefined

I need a debug log

**Comment by MC-1984** [comment]
`
synology.0 | 2020-05-20 10:53:29.235 | info | (2902) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
synology.0 | 2020-05-20 10:53:29.234 | info | (2902) terminating
synology.0 | 2020-05-20 10:53:29.102 | debug | (2902) cleaned everything up...
synology.0 | 2020-05-20 10:53:29.101 | error | (2902) TypeError: Cannot read property 'api' of undefined at sendPolling (/opt/iobroker/node_modules/iobroker.synology/main.js:1099:32) at queuePolling (/opt/iobroker/node_modules/iobroker.syn
synology.0 | 2020-05-20 10:53:29.099 | error | (2902) uncaught exception: Cannot read property 'api' of undefined
synology.0 | 2020-05-20 10:53:29.097 | debug | (2902) sendPolling. namePolling = slowPoll \| iteration = 0 \| poll = undefined
synology.0 | 2020-05-20 10:53:29.094 | debug | (2902) -----------------------------------------------------------------------------------------------------
synology.0 | 2020-05-20 10:53:28.993 | debug | (2902) setObject "VideoStation.info.version_string"
synology.0 | 2020-05-20 10:53:28.993 | debug | (2902) setObject "VideoStation.info.version"
synology.0 | 2020-05-20 10:53:28.992 | debug | (2902) setObject "VideoStation.info.transcoding_capability.transcode"
synology.0 | 2020-05-20 10:53:28.991 | debug | (2902) setObject "VideoStation.info.transcoding_capability.software_transcode"
synology.0 | 2020-05-20 10:53:28.990 | debug | (2902) setObject "VideoStation.info.transcoding_capability.remux"
synology.0 | 2020-05-20 10:53:28.989 | debug | (2902) setObject "VideoStation.info.transcoding_capability.hardware_transcode"
synology.0 | 2020-05-20 10:53:28.988 | debug | (2902) setObject "VideoStation.info.transcoding_capability.fhd_hardware_transcode"
synology.0 | 2020-05-20 10:53:28.988 | debug | (2902) setObject "VideoStation.info.transcoding_capability.dtv_transcode"
synology.0 | 2020-05-20 10:53:28.987 | debug | (2902) setObject "VideoStation.info.timezone_offset"
synology.0 | 2020-05-20 10:53:28.986 | debug | (2902) setObject "VideoStation.info.timezone"
synology.0 | 2020-05-20 10:53:28.985 | debug | (2902) setObject "VideoStation.info.privilege.sharing"
synology.0 | 2020-05-20 10:53:28.984 | debug | (2902) setObject "VideoStation.info.privilege.renderer"
synology.0 | 2020-05-20 10:53:28.983 | debug | (2902) setObject "VideoStation.info.privilege.offline_conversion"
synology.0 | 2020-05-20 10:53:28.982 | debug | (2902) setObject "VideoStation.info.privilege.dtv"
synology.0 | 2020-05-20 10:53:28.982 | debug | (2902) setObject "VideoStation.info.is_subtitle_search_enabled"
synology.0 | 2020-05-20 10:53:28.981 | debug | (2902) setObject "VideoStation.info.is_manager"
synology.0 | 2020-05-20 10:53:28.980 | debug | (2902) setObject "VideoStation.info.is_dtv_enabled"
synology.0 | 2020-05-20 10:53:28.979 | debug | (2902) setObject "FileStation.info.uid"
synology.0 | 2020-05-20 10:53:28.978 | debug | (2902) setObject "FileStation.info.system_codepage"
synology.0 | 2020-05-20 10:53:28.977 | debug | (2902) setObject "FileStation.info.support_virtual_protocol.2"
synology.0 | 2020-05-20 10:53:28.977 | debug | (2902) setObject "FileStation.info.support_virtual_protocol.1"
synology.0 | 2020-05-20 10:53:28.976 | debug | (2902) setObject "FileStation.info.support_virtual_protocol.0"
synology.0 | 2020-05-20 10:53:28.975 | debug | (2902) setObject "FileStation.info.support_virtual.enable_remote_mount"
synology.0 | 2020-05-20 10:53:28.974 | debug | (2902) setObject "FileStation.info.support_virtual.enable_iso_mount"
synology.0 | 2020-05-20 10:53:28.973 | debug | (2902) setObject "FileStation.info.support_vfs"
synology.0 | 2020-05-20 10:53:28.972 | debug | (2902) setObject "FileStation.info.support_sharing"
synology.0 | 2020-05-20 10:53:28.971 | debug | (2902) setObject "FileStation.info.support_file_request"
synology.0 | 2020-05-20 10:53:28.970 | debug | (2902) setObject "FileStation.info.items.1"
synology.0 | 2020-05-20 10:53:28.969 | debug | (2902) setObject "FileStation.info.items.0"
synology.0 | 2020-05-20 10:53:28.969 | debug | (2902) setObject "FileStation.info.is_manager"
synology.0 | 2020-05-20 10:53:28.968 | debug | (2902) setObject "FileStation.info.hostname"
synology.0 | 2020-05-20 10:53:28.967 | debug | (2902) setObject "FileStation.info.enable_list_usergrp"
synology.0 | 2020-05-20 10:53:28.966 | debug | (2902) setObject "DiskStationManager.info.version_string"
synology.0 | 2020-05-20 10:53:28.965 | debug | (2902) setObject "DiskStationManager.info.version"
synology.0 | 2020-05-20 10:53:28.964 | debug | (2902) setObject "DiskStationManager.info.uptime"
synology.0 | 2020-05-20 10:53:28.963 | debug | (2902) setObject "DiskStationManager.info.time"
synology.0 | 2020-05-20 10:53:28.962 | debug | (2902) setObject "DiskStationManager.info.temperature_warn"
synology.0 | 2020-05-20 10:53:28.961 | debug | (2902) setObject "DiskStationManager.info.temperature"
synology.0 | 2020-05-20 10:53:28.960 | debug | (2902) setObject "DiskStationManager.info.serial"
synology.0 | 2020-05-20 10:53:28.960 | debug | (2902) setObject "DiskStationManager.info.ram"
synology.0 | 2020-05-20 10:53:28.959 | debug | (2902) setObject "DiskStationManager.info.model"
synology.0 | 2020-05-20 10:53:28.956 | debug | (2902) setObject "DiskStationManager.info.codepage"
synology.0 | 2020-05-20 10:53:28.954 | debug | (2902) setStates
synology.0 | 2020-05-20 10:53:28.954 | debug | (2902) >>>>>>>>>>>>>>> Read all data, save received data.
synology.0 | 2020-05-20 10:53:28.953 | debug | (2902) -----------------------------------------------------------------------------------------------------
synology.0 | 2020-05-20 10:53:28.953 | debug | (2902) * Poll undefined
synology.0 | 2020-05-20 10:53:28.952 | debug | (2902) sendPolling. namePolling = firstPoll \| iteration = 10 \| poll = object
synology.0 | 2020-05-20 10:53:28.952 | debug | (2902) -----------------------------------------------------------------------------------------------------
synology.0 | 2020-05-20 10:53:28.951 | debug | (2902) * Poll undefined
synology.0 | 2020-05-20 10:53:28.951 | debug | (2902) sendPolling. namePolling = firstPoll \| iteration = 9 \| poll = object
synology.0 | 2020-05-20 10:53:28.950 | debug | (2902) -----------------------------------------------------------------------------------------------------
synology.0 | 2020-05-20 10:53:28.949 | debug | (2902) * Poll undefined
synology.0 | 2020-05-20 10:53:28.949 | debug | (2902) sendPolling. namePolling = firstPoll \| iteration = 8 \| poll = object
synology.0 | 2020-05-20 10:53:28.948 | debug | (2902) -----------------------------------------------------------------------------------------------------
synology.0 | 2020-05-20 10:53:28.948 | debug | (2902) * Poll undefined
synology.0 | 2020-05-20 10:53:28.947 | debug | (2902) sendPolling. namePolling = firstPoll \| iteration = 7 \| poll = object
synology.0 | 2020-05-20 10:53:28.946 | debug | (2902) -----------------------------------------------------------------------------------------------------
synology.0 | 2020-05-20 10:53:28.945 | debug | (2902) * Poll undefined
synology.0 | 2020-05-20 10:53:28.944 | debug | (2902) sendPolling. namePolling = firstPoll \| iteration = 6 \| poll = object
synology.0 | 2020-05-20 10:53:28.943 | debug | (2902) -----------------------------------------------------------------------------------------------------
synology.0 | 2020-05-20 10:52:58.940 | debug | (2902) Info - Response: {"is_dtv_enabled":false,"is_manager":true,"is_subtitle_search_enabled":false,"privilege":{"dtv":true,"offline_conversion":true,"renderer":true,"sharing":true},"timezone":"Amste
synology.0 | 2020-05-20 10:52:58.939 | debug | (2902) * The response is received, parse:
synology.0 | 2020-05-20 10:52:57.646 | debug | (2902) * Get info from (firstPoll) api: VS method: getInfo params: {}
synology.0 | 2020-05-20 10:52:57.645 | debug | (2902) sendPolling. namePolling = firstPoll \| iteration = 5 \| poll = object
synology.0 | 2020-05-20 10:52:57.644 | debug | (2902) -----------------------------------------------------------------------------------------------------
synology.0 | 2020-05-20 10:52:57.643 | debug | (2902) * Poll undefined
synology.0 | 2020-05-20 10:52:57.642 | debug | (2902) sendPolling. namePolling = firstPoll \| iteration = 4 \| poll = object
synology.0 | 2020-05-20 10:52:57.642 | debug | (2902) -----------------------------------------------------------------------------------------------------
synology.0 | 2020-05-20 10:52:57.641 | debug | (2902) * Poll undefined
synology.0 | 2020-05-20 10:52:57.640 | debug | (2902) sendPolling. namePolling = firstPoll \| iteration = 3 \| poll = object
synology.0 | 2020-05-20 10:52:57.639 | debug | (2902) -----------------------------------------------------------------------------------------------------
synology.0 | 2020-05-20 10:52:27.637 | debug | (2902) Info - Response: {"enable_list_usergrp":false,"hostname":"NAS","is_manager":true,"items":[{"gid":100},{"gid":101}],"support_file_request":true,"support_sharing":true,"support_vfs":true,"support
synology.0 | 2020-05-20 10:52:27.636 | debug | (2902) * The response is received, parse:
synology.0 | 2020-05-20 10:52:26.103 | debug | (2902) * Get info from (firstPoll) api: FS method: getInfo params: {}
synology.0 | 2020-05-20 10:52:26.103 | debug | (2902) sendPolling. namePolling = firstPoll \| iteration = 2 \| poll = object
synology.0 | 2020-05-20 10:52:26.102 | debug | (2902) -----------------------------------------------------------------------------------------------------
synology.0 | 2020-05-20 10:51:56.100 | debug | (2902) Info - Response: {"codepage":"enu","model":"DS918+","ram":8192,"serial":"1790PDN454408","temperature":41,"temperature_warn":false,"time":"Wed May 20 10:51:56 2020","uptime":2162888,"version":"2
synology.0 | 2020-05-20 10:51:56.099 | debug | (2902) * The response is received, parse:
synology.0 | 2020-05-20 10:51:56.016 | debug | (2902) * Get info from (firstPoll) api: DSM method: getInfo params: {}
synology.0 | 2020-05-20 10:51:56.016 | debug | (2902) sendPolling. namePolling = firstPoll \| iteration = 1 \| poll = object
synology.0 | 2020-05-20 10:51:56.015 | debug | (2902) -----------------------------------------------------------------------------------------------------
synology.0 | 2020-05-20 10:51:26.014 | debug | (2902) InstallingPackets - Response: {"diskList":"","packages":{"AntiVirus":true,"HyperBackup":true,"HyperBackupVault":true,"LogCenter":true,"NoteStation":true,"OAuthService":true,"PDFViewer":true,"Ph
synology.0 | 2020-05-20 10:51:26.012 | debug | (2902) * The response is received, parse:
synology.0 | 2020-05-20 10:51:23.922 | debug | (2902) * Get info from (firstPoll) api: DSM method: getPollingData params: {}
synology.0 | 2020-05-20 10:51:23.921 | debug | (2902) sendPolling. namePolling = firstPoll \| iteration = 0 \| poll = object
synology.0 | 2020-05-20 10:51:23.919 | debug | (2902) -----------------------------------------------------------------------------------------------------
synology.0 | 2020-05-20 10:50:53.916 | error | (2902) *** ERROR : src: *sendPolling syno[dsm][getPollingData] code: 404 message: Failed to authenticate 2-step verification code
synology.0 | 2020-05-20 10:50:53.915 | debug | (2902) * No response, read next.
synology.0 | 2020-05-20 10:50:49.012 | debug | (2902) * Get info from (firstPoll) api: DSM method: getPollingData params: {}
synology.0 | 2020-05-20 10:50:49.012 | debug | (2902) sendPolling. namePolling = firstPoll \| iteration = 0 \| poll = object
synology.0 | 2020-05-20 10:50:49.011 | debug | (2902) -----------------------------------------------------------------------------------------------------
synology.0 | 2020-05-20 10:50:47.002 | info | (2902) starting. Version 0.1.15 in /opt/iobroker/node_modules/iobroker.synology, node: v12.16.3, js-controller: 3.1.4
synology.0 | 2020-05-20 10:50:45.257 | debug | (2902) States create System PubSub Client
synology.0 | 2020-05-20 10:50:45.253 | debug | (2902) States create User PubSub Client
synology.0 | 2020-05-20 10:50:45.245 | debug | (2902) Redis States: Use Redis connection: 127.0.0.1:9000
synology.0 | 2020-05-20 10:50:45.243 | debug | (2902) objectDB connected
synology.0 | 2020-05-20 10:50:45.236 | debug | (2902) Objects connected to redis: 127.0.0.1:9001
synology.0 | 2020-05-20 10:50:45.204 | debug | (2902) Objects client initialize lua scripts
synology.0 | 2020-05-20 10:50:45.202 | debug | (2902) Objects create User PubSub Client
synology.0 | 2020-05-20 10:50:45.201 | debug | (2902) Objects create System PubSub Client
synology.0 | 2020-05-20 10:50:45.195 | debug | (2902) Objects client ready ... initialize now
synology.0 | 2020-05-20 10:50:45.157 | debug | (2902) Redis Objects: Use Redis connection: 127.0.0.1:9001
synology.0 | 2020-05-20 10:50:40.934 | info | (2759) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
synology.0 | 2020-05-20 10:50:40.932 | info | (2759) terminating
synology.0 | 2020-05-20 10:50:40.931 | debug | (2759) cleaned everything up...
synology.0 | 2020-05-20 10:50:40.929 | info | (2759) Got terminate signal TERMINATE_YOURSELF
synology.0 | 2020-05-20 10:50:39.799 | debug | (2759) InstallingPackets - Response: {"diskList":"","packages":{"AntiVirus":true,"HyperBackup":true,"HyperBackupVault":true,"LogCenter":true,"NoteStation":true,"OAuthService":true,"PDFViewer":true,"P
synology.0 | 2020-05-20 10:50:39.797 | debug | (2759) * The response is received, parse:
synology.0 | 2020-05-20 10:50:38.901 | debug | (2759) * Get info from (firstPoll) api: DSM method: getPollingData params: {}
synology.0 | 2020-05-20 10:50:38.900 | debug | (2759) sendPolling. namePolling = firstPoll \| iteration = 0 \| poll = object
synology.0 | 2020-05-20 10:50:38.899 | debug | (2759) -----------------------------------------------------------------------------------------------------
synology.0 | 2020-05-20 10:50:36.689 | info | (2759) starting. Version 0.1.15 in /opt/iobroker/node_modules/iobroker.synology, node: v12.16.3, js-controller: 3.1.4

`

**Comment by instalator** [comment]
I don’t understand what the error is, tried to restart the server?

**Comment by instalator** [comment]
Update from github and test

**Comment by tobasium** [comment]
Hi in Version 0.1.16 all works fine for me now.

**Comment by Ilovegym66** [comment]
Hi, thank you, 0.1.16 works very good.

**Comment by MC-1984** [comment]
Thank you very much, it works perfectly!
