### ISSUE TITLE
error nach update DSM 6.2.3-25426

### ISSUE THREAD

**Issue by XBiT2k** [instalator/ioBroker.synology#48]
Hallo,
Nach dem DSM update erhalte ich diese Fehler im Log:
`
synology.0 | 2020-05-28 07:19:32.900 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[as][listRemotePlayers] Error -TypeError: Cannot read property 'forEach' of undefined
-- | -- | -- | --
synology.0 | 2020-05-28 07:18:32.696 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[ss][listCameras] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:18:32.495 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[as][listRadios] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:18:32.362 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[as][listRemotePlayers] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:17:32.701 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[ss][listCameras] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:17:32.486 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[as][listRadios] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:17:32.320 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[as][listRemotePlayers] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:16:32.308 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[ss][listCameras] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:16:32.090 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[as][listRadios] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:16:31.865 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[as][listRemotePlayers] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:13:31.002 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[ss][listCameras] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:13:30.796 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[as][listRadios] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:13:30.654 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[as][listRemotePlayers] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:11:30.466 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[ss][listCameras] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:11:30.237 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[as][listRadios] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:11:30.072 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[as][listRemotePlayers] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:10:29.839 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[as][listRemotePlayers] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:09:29.596 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[as][listRemotePlayers] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:07:28.921 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[as][listRemotePlayers] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:04:28.611 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[ss][listCameras] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:04:28.393 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[as][listRadios] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:04:28.228 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[as][listRemotePlayers] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:03:27.200 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[as][listRemotePlayers] Error -TypeError: Cannot read property 'forEach' of undefined
synology.0 | 2020-05-28 07:01:26.857 | error | (1286) *** ERROR : src: ParseFunction code: undefined message: syno[as][listRemotePlayers] Error -TypeError: Cannot read property 'forEach' of undefined
`

**Comment by instalator** [comment]
what version of the adapter?

**Comment by XBiT2k** [comment]
Sorry my mistake
had version 0.1.8 updated to 0.1.18 and it's okay.
