### ISSUE TITLE
Errors with API version 5.2

### ISSUE THREAD

**Issue by christofkac** [instalator/ioBroker.synology#50]
I'm using the latest version of the synology plugin with my old DS210j running DSM 5.2
I can read out values of the object of DiskStationManager successfully but get still the following errors:

synology.1	2020-07-01 22:56:58.907	error	(3565) *** ERROR : src: *sendPolling syno[dsm][getSystemStatus] code: 102 message: The requested API does not exist
synology.1	2020-07-01 22:56:56.766	error	(3565) *** ERROR : src: *sendPolling syno[fs][listSharings] code: 102 message: The requested API does not exist
synology.1	2020-07-01 22:56:55.846	error	(3565) *** ERROR : src: *sendPolling syno[dsm][getInfo] code: 102 message: The requested API does not exist
synology.1	2020-07-01 22:56:55.641	error	(3565) *** ERROR : src: *sendPolling syno[dsm][getSystemStatus] code: 102 message: The requested API does not exist
synology.1	2020-07-01 22:56:53.547	error	(3565) *** ERROR : src: *sendPolling syno[fs][listSharings] code: 102 message: The requested API does not exist
synology.1	2020-07-01 22:56:52.403	error	(3565) *** ERROR : src: *sendPolling syno[dsm][getInfo] code: 102 message: The requested API does not exist

With my old installation of ioBroker using synology adapter version 0.0.4 I don't see any errors.

Any idea what is wrong?
Bye
Christof

**Comment by Knallochse** [comment]
Same Problem here

**Comment by instalator** [comment]
API 5 does not support these methods. Reduced the output of errors to the log.
