### ISSUE TITLE
hdd_info doesn't show all Drives

### ISSUE THREAD

**Issue by DirtyAtze** [instalator/ioBroker.synology#51]
Hey guys!

I had 2 HDD Drives and one SSD Cache Drive installed into my DS720+.
In 'Objects' it showed just one HDD and the SSD Drive states. Today I installed another SSD Cache and now it only shows the 2 SSD Cache Drives. The States of the HDD are gone.
Is there any Known Issue?

**Comment by Ilovegym66** [comment]
Good, that you see this, in my Syno the SSD-Cache-Drives are not shown in the adapter.. only the HDD-Drives.. ( have a 918+ with 4 HDD and 2 SSD-Caches.).

**Comment by instalator** [comment]
Send me a debug log.

**Comment by Ilovegym66** [comment]
ah, sorry, for the late feedback, here the logfile. I have a 918+ with 2 SSD and 4 HDD, I don t know, if the api send all the informations.. 
[synology.log.txt](https://github.com/instalator/ioBroker.synology/files/6236744/synology.log.txt)

**Comment by instalator** [comment]
Check on version 1.0.0

**Comment by Ilovegym66** [comment]
yeah, thank you, works fine now! Well done!
Show me all SATA and SSD drives.
