### ISSUE TITLE
Adapter installation not possible

### ISSUE THREAD

**Issue by Castlehub** [instalator/ioBroker.synology#52]
Hey.

The installation of the adapter (Vers. 0.1.18) ends with the following error message.

Is there any Known Issue?

**Error message:**

Fertig mit Fehler: host.iobroker Cannot install iobroker.synology@0.1.18: 1

$ ./iobroker add synology  --host iobroker
NPM version: 6.14.6
npm install iobroker.synology@0.1.18 --loglevel error --prefix "/opt/iobroker" (System call)
npm 
ERR! code ECONNREFUSEDnpm ERR! errno ECONNREFUSEDnpm 
ERR! FetchError: request to https://github.com/homeinstalator/syno/tarball/master/ failed, reason: connect ECONNREFUSED 0.0.0.0:443npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)npm ERR!     at ClientRequest.emit (events.js:315:20)npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:426:9)npm ERR!     at TLSSocket.emit (events.js:315:20)npm ERR!     at emitErrorNT (internal/streams/destroy.js:92:8)npm ERR!     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:84:21)npm ERR!  FetchError: request to https://github.com/homeinstalator/syno/tarball/master/ failed, reason: connect ECONNREFUSED 0.0.0.0:443npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)npm ERR!     at ClientRequest.emit (events.js:315:20)npm ERR!
     at TLSSocket.socketErrorListener (_http_client.js:426:9)npm ERR!     at TLSSocket.emit (events.js:315:20)npm ERR!     at emitErrorNT (internal/streams/destroy.js:92:8)npm ERR!     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:84:21) {npm ERR!   type: 'system',npm ERR!   errno: 'ECONNREFUSED',npm ERR!   code: 'ECONNREFUSED',npm ERR!   parent: 'iobroker.synology'npm ERR! }npm ERR! npm
 ERR! If you are behind a proxy, please make sure that thenpm ERR! 'proxy' config is set properly.  See: 'npm help config'
npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2020-09-04T16_14_47_739Z-debug.log
ERROR: host.iobroker Cannot install iobroker.synology@0.1.18: 1
ERROR: process exited with code 25

**Comment by instalator** [comment]
probably the problem is the internet.
