### ISSUE TITLE
Feature Request - Reduce the error messages in iobroker log

### ISSUE THREAD

**Issue by christi-ko** [instalator/ioBroker.synology#56]
Hi, i am using the adapter with my synology NAS. However my NAS ist not running all the day but only some hours daily, therefore i get a lot of the following messages:

The messages while not powered:
*** ERROR : src: *sendPolling syno[dsm][getInfo] code: EHOSTUNREACH message: connect EHOSTUNREACH 192.168.xxx.xx:xxxx
*** ERROR : src: *sendPolling syno[dsm][infoSystem] code: ECONNREFUSED message: connect ECONNREFUSED 

192.168.xxx.xx:xxxx
The messages which power on:
*** ERROR : src: *sendPolling syno[dsm][getInfo] code: 100 message: Unknown error
*** ERROR : src: *sendPolling syno[dsm][getSystemStatus] code: 100 message: Unknown error
*** ERROR : src: *sendPolling syno[dsm][getSystemUtilization] code: 100 message: Unknown error
*** ERROR : src: *sendPolling syno[fs][listSharings] code: 100 message: Unknown error

The messages while shutting down:
I think they are the same as during power on.

and some others for sure, i may missed some of those ...

Would it be possible to reduce that message types which do come up for an synology which is starting / shutting down / not running to a lower level e.g. warn or info. This would give the user the possiblity to hide a lot of not critical messages in the log.

Also a change to show the message only once a while (lower polling rate or whatever) may be a solution. 

regards
Christian

**Comment by instalator** [comment]
Fixed in 0.1.19
