### ISSUE TITLE
shut down not working

### ISSUE THREAD

**Issue by koburg** [instalator/ioBroker.synology#57]
I got the below error trying to shutdown on api 6.2.3 

`
  |   |   |  
-- | -- | -- | --
synology.0 | 2020-11-03 17:36:19.840 | error | (1846) *** ERROR : src: function send: [dsm][shutdownSystem] code: 117 message: Unknown error
`

**Comment by p3pp0** [comment]
same for me. Not working

**Comment by instalator** [comment]
what version of api? We need a debug log at the time of the error.

**Comment by instalator** [comment]
I checked on my device with the specified version, it works fine.
