### ISSUE TITLE
Adapter updatet Werte nicht, nur einmal beim starten des Adapters

### ISSUE THREAD

**Issue by Lucifor1976** [instalator/ioBroker.synology#59]
Hallo,
Hello,

DE:Der Adapter updated keine Werte innerhalb der eingestellten Zeit. Die Werte werden einmalig beim starten des Adapters gelesen. Danach nur noch Zeit und CPU Load.

EN: The Adapter doesn´t udpate any States anymore, only on Start the Adapter the States are updatet ones.
See Log and Screens. Only Time and CPU Load will be updatet continously.

Debuglog:
[synoLog.txt](https://github.com/instalator/ioBroker.synology/files/5684317/synoLog.txt)

Screenshot Objekte:
![Bildschirmfoto 2020-12-13 um 08 42 25](https://user-images.githubusercontent.com/67290625/102006280-386f5400-3d20-11eb-89d8-deabc01c7c6e.png)

Screenshot Settings:
![Bildschirmfoto 2020-12-13 um 08 48 34](https://user-images.githubusercontent.com/67290625/102006284-4a50f700-3d20-11eb-94ac-9fa07351fb2d.png)

**Comment by instalator** [comment]
What data do you always need to update?

**Comment by guergen1** [comment]
z.B. Uptime

**Comment by instalator** [comment]
Update adapter from github

**Comment by instalator** [comment]
This is what you need?

**Comment by guergen1** [comment]
Yes, that ist what I mean! Thank you!
