### ISSUE TITLE
Two questions about one problem

### ISSUE THREAD

**Issue by scripthase** [instalator/ioBroker.synology#61]
Hello everybody,

I would like to look at the data point "motionDetected" with a Blockly script and if this changes to "true" I would like to execute an action. Unfortunately, this value is no longer updated after an update to DSM 7.0 and remains permanently on "false". The API version is set to 6.2.2.

Furthermore, I would like to feed the data point "getSnapshotCamera" with the Blockly script so that it can put a picture in the iobroker folder. This does not work with Blockly either! However, if I manually write the camera ID into the data point, the screenshot will be saved.

Can someone help me with both of my problems?
Thanks in advance.

Love from
Scripthase

**Comment by instalator** [comment]
Adapter does not support API DSM 7.0
