### ISSUE TITLE
synology Adapter

### ISSUE THREAD

**Issue by marcus200289** [instalator/ioBroker.synology#62]
Hey ein guten Abend Leute ,
ich habe folgendes Problem ,seit Synology eine neues Betriebssystem bzw. eine neue Version hat passt natürlich nichts mehr. Ich kann leider im Adapter nicht auf die DSM Version 7.0 wechseln sondern nur auf Version 6.2.3. Laut Iobroker ist der Adapter Grün,
ich kann aber die Kameras nicht mehr in der Vis einbinden. Vielleicht habt ihr eine Lösung für mich. Wünsche euch noch ein schön Abend und Einen guten Rutsch.

**Comment by instalator** [comment]
The adapter does not support api version 7 and as far as I know this version is still beta. In addition, there is not even documentation for the api version 7
