### ISSUE TITLE
nach js-controler update jede Menge kommen Warnungen

### ISSUE THREAD

**Issue by Tomscloud** [instalator/ioBroker.synology#65]
Hi
JS-Controller ginbt es jetzt als 3.2.10 in latest, nachdem man das update macht kommen im Log all diese Warnungen:

Kannst du da was machen?

synology.0 | 2021-01-24 10:44:51.351 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.cover"  has no existing object, this might lead to an error in future versions
-- | -- | -- | --
synology.0 | 2021-01-24 10:44:51.351 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.current_play"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.349 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.playlist"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.348 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.seek"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.346 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.duration_sec"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.345 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.current_elapsed"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.343 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.current_duration"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.341 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.duration"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.340 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.bitrate"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.338 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.shuffle"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.335 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.repeat"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.332 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.path"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.330 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.title"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.327 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.song_id"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.325 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.year"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.322 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.genre"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.321 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.artist"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.319 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.album"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.319 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.volume"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.316 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.playlist_total"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.315 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.state_playing"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.313 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.cover"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.310 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.current_play"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.307 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.playlist"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.305 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.seek" has  no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.304 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.duration_sec"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.299 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.current_elapsed"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.297 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.current_duration"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.294 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.duration"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.292 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.bitrate"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.288 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.shuffle"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.286 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.repeat"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.285 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.path" has  no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.285 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.title"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.284 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.song_id"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.284 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.year" has  no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.283 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.genre"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.282 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.artist"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.281 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.album"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.281 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.volume"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.280 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.playlist_total"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:51.280 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.state_playing"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.652 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.clearPlaylist"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.651 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.Browser"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.650 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.play_track"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.649 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.play_folder"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.649 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.next"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.648 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.prev"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.646 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.play"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.645 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.pause"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.643 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.stop"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.641 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.player_name"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.640 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:39d72ca8-3bdb-11e3-8c73-0011e11d7769.online"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.639 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.clearPlaylist"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.637 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.Browser"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.635 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.play_track"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.633 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.play_folder"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.631 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.next" has  no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.629 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.prev" has  no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.627 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.play" has  no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.625 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.pause"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.623 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.stop" has  no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.618 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.player_name"  has no existing object, this might lead to an error in future versions
synology.0 | 2021-01-24 10:44:48.616 | warn | (1352813) State  "synology.0.AudioStation.players.uuid:RINCON_347E5C346D5201400.online"  has no existing object, this might lead to an error in future versions

**Comment by instalator** [comment]
Send me a RAW of one of the objects listed in the error.

**Comment by Tomscloud** [comment]
how can i get this? 
But there is no longer this warnings in my log.

**Comment by instalator** [comment]
Resolved

**Comment by Tomscloud** [comment]
ok, i see there is an new update today
