### ISSUE TITLE
JS-Controller 3.3 - wrong type "number" but has to be "string"

### ISSUE THREAD

**Issue by kueppert** [instalator/ioBroker.synology#78]
synology.0 | 2021-04-30 10:02:40.095 | warn | (20146) State value to set for "synology.0.DiskStationManager.info.uptime" has wrong type "number" but has to be "string"

**Versions:**  
 - Adapter version: <1.0.0>
 - JS-Controller version: <3.3>
 - Operating system: <buster>

**Comment by TheBrain26** [comment]
Same Issues

https://github.com/ioBroker/ioBroker.js-controller/issues/1299#issuecomment-829967503

**Comment by MMeinhardt1** [comment]
I have also some warnings, see below

Adaptername | Uhrzeit | Status | Meldung
-- | -- | -- | --
synology.0 | 2021-05-01 13:38:50.776 | warn | State value to set for "synology.0.DiskStationManager.vol_info.volume_1.used" has wrong type "string" but has to be "number"
synology.0 | 2021-05-01 13:38:50.765 | warn | State  value to set for  "synology.0.DiskStationManager.vol_info.volume_1.used_size" has wrong  type "string" but has to be "number"
synology.0 | 2021-05-01 13:38:50.763 | warn | State  value to set for  "synology.0.DiskStationManager.vol_info.volume_1.total_size" has wrong  type "string" but has to be "number"
synology.0 | 2021-05-01 13:38:50.753 | warn | State  value to set for  "synology.0.DiskStationManager.hdd_info.sata_drive_2.capacity" has wrong  type "string" but has to be "number"
synology.0 | 2021-05-01 13:38:50.750 | warn | State  value to set for  "synology.0.DiskStationManager.hdd_info.sata_drive_2.ebox_order" has  wrong type "number" but has to be "string"
synology.0 | 2021-05-01 13:38:50.747 | warn | State  value to set for  "synology.0.DiskStationManager.hdd_info.sata_drive_1.capacity" has wrong  type "string" but has to be "number"
synology.0 | 2021-05-01 13:38:50.733 | warn | State  value to set for  "synology.0.DiskStationManager.hdd_info.sata_drive_1.ebox_order" has  wrong type "number" but has to be "string"
synology.0 | 2021-05-01 13:38:50.731 | warn | State value to set for "synology.0.DiskStationManager.info.upgrade_ready" has wrong type "boolean" but has to be "string"
synology.0 | 2021-05-01 13:38:50.730 | warn | State value to set for "synology.0.DiskStationManager.info.is_system_crashed" has wrong type "boolean" but has to be "string"
synology.0 | 2021-05-01 13:38:50.728 | warn | State value to set for "synology.0.DiskStationManager.info.memory_size" has wrong type "number" but has to be "string"
synology.0 | 2021-05-01 13:38:50.725 | warn | State value to set for "synology.0.DiskStationManager.info.uptime" has wrong type "number" but has to be "string"

**Comment by MMeinhardt1** [comment]
The fixed version is not available
